### ISSUE TITLE
Provisionamiento opcional con otra tecnología

### ISSUE THREAD

**Issue by fblupi** [fblupi/GEventator#14]
Chef, Salt o Puppet

**Comment by AythaE** [comment]
Comprobado funcionamiento de provisionamiento en AWS con Ubuntu 14.04

![Imagen provisionamiento](https://raw.githubusercontent.com/AythaE/DeFesti/gh-pages/images/Ejecucion%20chef%20fblupi.png "Imagen provisionamiento")

**Comment by joseangeldiazg** [comment]
Probado provisionamiento con chef. Funciona correctamente. 

<img width="687" alt="captura de pantalla 2016-11-24 a las 17 00 59" src="https://cloud.githubusercontent.com/assets/10519534/20604650/be362c82-b267-11e6-90b1-59f213db818b.png">

**Comment by Pablo126** [comment]
Comprobado el provisionamiento con Chef en máquina virtual AWS Ubuntu 14.04
![cheffblupi](https://cloud.githubusercontent.com/assets/6097945/20802559/b0b9e7d0-b7ec-11e6-84c3-5c18642db44d.png)
