### ISSUE TITLE
Orquestar varias máquinas virtuales provisionando con Ansible

### ISSUE THREAD

**Issue by fblupi** [fblupi/GEventator#20]

**Comment by AythaE** [comment]
Probada orquestación correctamente.

![Prueba orquestacion 1](https://raw.githubusercontent.com/AythaE/DeFesti/gh-pages/images/Fblupi_orquestacion1.png)

![Prueba orquestacion 2](https://raw.githubusercontent.com/AythaE/DeFesti/gh-pages/images/Fblupi_orquestacion2.png)

**Comment by grivasgervilla** [comment]
Se ha probado la orquestación y funciona correctamente. Estaría bien añadir en las intrucciones la necesidad de cambiar la región de las instancias AWS en el Vagrantfile por aquella en la que el usuario haya creado las claves:

![imagen](https://cloud.githubusercontent.com/assets/7707062/21136443/f49dceca-c125-11e6-9884-c44c5b2e047c.png)
![imagen](https://cloud.githubusercontent.com/assets/7707062/21136467/0f7754d2-c126-11e6-8199-91a81faabdf0.png)
