### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by fblupi** [fblupi/GEventator#23]

**Comment by AythaE** [comment]
Contenedor probado siguiendo las instrucciones y funcionamiento correcto


![Descarga contenedor docker fblupi](https://raw.githubusercontent.com/AythaE/DeFesti/gh-pages/images/descarga%20docker%20fblupi.png "Descarga contenedor docker fblupi")

![Acceso contenedor fblupi](https://raw.githubusercontent.com/AythaE/DeFesti/gh-pages/images/Acceso%20contendor%20fblupi.png "Acceso contenedor fblupi")
